name: Automacao Web

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

jobs:
  RunTest:
    runs-on: windows-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Debug DNS
        run: |
          nslookup qazando.com
          ping -c 4 qazando.com

      - name: Run tests
        run: mvn clean test -Dbrowser=chrome-ci

      - name: Upload Relat√≥rio Extent
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Automacao-Web
          path: target/extent-report.html